export default {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    UPDATE_TODOS: 'UPDATE_TODOS',
    MARK_IMPORTANT: 'MARK_IMPORTANT',
    FILTER_TODOS: 'FILTER_TODOS',
}
